language: c

matrix:
 include:
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        packages:
	 - gcc-arm-none-eabi
	 - qemu


notifications:
  email: false

before_install:
  - git submodule update --init --recursive
  - mkdir test/build
  - cd test/build && cmake .. && make -j2


script:
  - make ci
