language: c

matrix:
 include:
  - os: linux
    dist: trusty
    compiler: gcc

notifications:
  email: false

cache:
  directories:
   - /home/travis/build/culshoefer/trains/test/googletest/build

before_install:
  - sudo apt-get install qemu gcc-arm-none-eabi libboost-all-dev doxygen
  - git submodule update --init --recursive
  - mkdir test/build
  - cd test/googletest
  - chmod +x ci/travis.sh
  - ./ci/travis.sh
  - mv googletest gtest

env:
  -GTEST=/home/travis/build/culshoefer/trains/test/googletest/gtest/include
  -LIBGTEST=/home/travis/build/culshoefer/trains/test/googletest/build/googlemock/gtest/libgtest.a
  -BOOST=/usr/local/include/boost
  -armlibs=/usr/lib/gcc/arm-none-eabi/4.8.2

script:
  - which doxygen
  - ls $GTEST
  - ls $LIBGTEST
  - ls $armlibs
  - pwd
  - set -e
  - cd ../..
  - make ci
